/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.p1_pss_2020_2.view;

import com.pss.p1_pss_2020_2.collection.FuncionarioCollection;
import com.pss.p1_pss_2020_2.model.Funcionario;
import com.pss.p1_pss_2020_2.presenter.BuscarFuncionarioPresenter;
import com.pss.p1_pss_2020_2.presenter.BuscarFuncionarioPresenter;
import com.pss.p1_pss_2020_2.presenter.CalcularSalarioPresenter;
import com.pss.p1_pss_2020_2.presenter.FuncionarioPresenter;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author mayco
 */
public class PrincipalView extends javax.swing.JFrame {
    private Funcionario funcionario;
    private FuncionarioCollection funcionarios = FuncionarioCollection.getInstance();

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        setLocationRelativeTo(this.getParent());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblQtdFuncionarios = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFuncionario = new javax.swing.JMenu();
        mnNovoFuncionario = new javax.swing.JMenuItem();
        mnBuscarFuncionario = new javax.swing.JMenuItem();
        mnSalario = new javax.swing.JMenu();
        mnCalculaSalario = new javax.swing.JMenuItem();
        mnFerramentas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Pessoas");

        lblQtdFuncionarios.setText("Funcionários:");

        lblQtd.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(lblQtdFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdFuncionarios)
                    .addComponent(lblQtd))
                .addGap(57, 57, 57))
        );

        mnFuncionario.setText("Funcionarios");
        mnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFuncionarioActionPerformed(evt);
            }
        });

        mnNovoFuncionario.setText("Novo Funcionário");
        mnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNovoFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(mnNovoFuncionario);

        mnBuscarFuncionario.setText("Buscar Funcionário");
        mnBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscarFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(mnBuscarFuncionario);

        jMenuBar1.add(mnFuncionario);

        mnSalario.setText("Salario");
        mnSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalarioActionPerformed(evt);
            }
        });

        mnCalculaSalario.setText("Calcular salário");
        mnCalculaSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCalculaSalarioActionPerformed(evt);
            }
        });
        mnSalario.add(mnCalculaSalario);

        jMenuBar1.add(mnSalario);

        mnFerramentas.setText("Ferramentas");
        jMenuBar1.add(mnFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFuncionarioActionPerformed
        
    }//GEN-LAST:event_mnFuncionarioActionPerformed

    private void mnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNovoFuncionarioActionPerformed
        new FuncionarioPresenter(funcionario);
    }//GEN-LAST:event_mnNovoFuncionarioActionPerformed

    private void mnBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscarFuncionarioActionPerformed
        BuscarFuncionarioView.getInstance();
    }//GEN-LAST:event_mnBuscarFuncionarioActionPerformed

    private void mnSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalarioActionPerformed
        
    }//GEN-LAST:event_mnSalarioActionPerformed

    private void mnCalculaSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCalculaSalarioActionPerformed
        CalcularSalarioPresenter.getInstance().getView().setVisible(true);
    }//GEN-LAST:event_mnCalculaSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblQtdFuncionarios;
    private javax.swing.JMenuItem mnBuscarFuncionario;
    private javax.swing.JMenuItem mnCalculaSalario;
    private javax.swing.JMenu mnFerramentas;
    private javax.swing.JMenu mnFuncionario;
    private javax.swing.JMenuItem mnNovoFuncionario;
    private javax.swing.JMenu mnSalario;
    // End of variables declaration//GEN-END:variables


    public JLabel getLblQtd() {
        return lblQtd;
    }

    
    
}
